### ISSUE TITLE
Can't execute the FirstProject sample

### ISSUE THREAD

**Issue by paulohva** [bonniee/learning-react-native#37]
After type:
```
$ npm install
```
Then:
```
$ react-native run-android
```
I had this error message:

> *Super expression must either be null or a function, not undefined

Current pachage.json file:
```json
{
  "name": "Project",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^15.0.2",
    "react-native": "^0.26.3"
  }
}
```

> node.js: v6.3.1
> npm: v3.10.3
> os: Windows 10

**Comment by jeffcarey** [comment]
In case you are still having this issue (or for anyone else experiencing it), you are probably better off just running "react-native init FirstProject" rather than cloning the directory from Github. There are some subtle but important differences caused by the latest versions of react-native and react.

**Comment by paulohva** [comment]
I did that but I had to adapt the code to the newer syntax. Anyways it worked, thanks :)
